### PR TITLE
Added sanic + mongo application 

### PR DESCRIPTION
**Pull request by officialasishkumar**

### CODE REVIEW

**Comment by officialasishkumar** [comment]
@nehagup @Sonichigo

**Comment by Sonichigo** [comment]
@officialasishkumar you can mark this PR ready for review, once you have added keploy tests and postman testcases.

**Comment by Swpn0neel** [comment]
LGTM! But this PR still doesn't include the postman and keploy testcases!

**Review by Swpn0neel — CHANGES_REQUESTED** [review]
Kindly add the test cases for this app

**Pull request closed without merging**
